version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
